### ISSUE TITLE
WWToLNuQQ processed twice

### ISSUE THREAD

**Issue by alesaggio** [cp3-llbb/Datasets#54]
WWToLNuQQ_13TeV-powheg_Summer16MiniAODv2 is processed twice

**Comment by pieterdavid** [comment]
Doesn't crab complain when submitting the second task?

**Comment by OlivierBondu** [comment]
it probably is, I have to admit I am not carefully checking the submission logs.... in any case only one task was created for this one, that is for sure

**Comment by pieterdavid** [comment]
yes, then it should say that the task directory already exists, and not submit a second time. Anyway, better to fix it :-)

**Comment by OlivierBondu** [comment]
see https://github.com/cp3-llbb/Datasets/pull/55 :wink:
